<?php
/**
 * @file
 * Code for the Drupal Cebu 2014 Map.
 */

/**
 * Implements hook_block_info().
 * This hook declares what blocks are provided by the module.
 */
function drupalcebu2014_map_block_info() {
  $blocks = array();
  $blocks['drupalcebu2014_map_text'] = array(
    'info' => t('Drupal Cebu 2014 Map'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 * This hook declares configuration options for blocks provided by this module.
 */
function drupalcebu2014_map_block_configure($delta = '') {
  $form = array();
  if ($delta == 'drupalcebu2014_map_text') {
    $form['drupalcebu2014_map_text'] = array(
      '#type' => 'text_format',
      '#title' => t('Map Content'),
      '#row' => 5,
      '#description' => t('This text will appear in the map block.'),
      '#default_value' => _drupalcebu2014_map_default(),
      '#format' => 'full_html',
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function drupalcebu2014_map_block_save($delta = '', $edit = array()) {
  if ($delta == 'drupalcebu2014_map_text') {
    // Have Drupal save the string to the database.
    variable_set('drupalcebu2014_map_text', $edit['drupalcebu2014_map_text']);
  }
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function drupalcebu2014_map_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'drupalcebu2014_map_text':
      $block['content'] = array(
        '#markup' => _drupalcebu2014_map_default(),
      );
      break;
  }
  return $block;
}

/**
 * Provides default value for map content
 */
function _drupalcebu2014_map_default() {
  $mark_up = '
        <div class="venue-info">
            <h3 class="venue-label">Venue</h3>
            <p class="venue-address">UNIVERSITY OF SAN CARLOS - Talamban Campus. Nasipit, Talamban Cebu City.</p>
          </div>
          <iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d3924.8531820579547!2d123.9109376342627!3d10.353622172260941!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sUniversity+of+San+Carlos%2C+Talamban!5e0!3m2!1sen!2sph!4v1409822043976" width="100%" height="700px" frameborder="0" style="border:0"></iframe>
        </div>';

  return variable_get('drupalcebu2014_map_text', $mark_up);
}
